### ISSUE TITLE
If it throws some curl error the fix is here

### ISSUE THREAD

**Issue by d1pakda5** [abdilahrf/shania#2]
Error: relocation error: curl: symbol curl_url_get version CURL_OPENSSL_4 not defined in file libcurl.so.4 with link time reference

Fix: 
locate libcurl.so.4

result will be like this
/home/chenjian/software/curl-7.20.0/lib/.libs/libcurl.so.4
/home/chenjian/software/curl-7.20.0/lib/.libs/libcurl.so.4.2.0
/usr/lib/x86_64-linux-gnu/libcurl.so.4
/usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0
/usr/local/lib/libcurl.so.4
/usr/local/lib/libcurl.so.4.2.0

sudo rm /usr/local/lib/libcurl.so.4
sudo ln -s /usr/lib/x86_64-linux-gnu/libcurl.so.4.3.0 /usr/local/lib/libcurl.so.4

**Comment by abdilahrf** [comment]
@d1pakda5 : Thanks for sharing workaround about an errors
i will mention this later if someone asking the same question
